spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/customers;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
  thymeleaf.cache: false
security.basic.enabled: false
---
spring:
  profiles: heroku
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  thymeleaf.cache: true
security.basic.enabled: false